// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: models/Product.proto

#include "models/Product.pb.h"
#include "models/Product.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace gRPCTest {
namespace Protos {
namespace Models {

} // namespace gRPCTest
} // namespace Protos
} // namespace Models

