// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: common/ServiceStatus.proto

#include "common/ServiceStatus.pb.h"
#include "common/ServiceStatus.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace gRPCTest {
namespace Protos {
namespace Services {

} // namespace gRPCTest
} // namespace Protos
} // namespace Services

